### ISSUE TITLE
Issue with starting the docker 

### ISSUE THREAD

**Issue by tfrostig** [AlexEMG/Docker4DeepLabCut#3]
Following the instructions I encounter a problem when running the line 
GPU=1 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut --name alex_GPU1 dlc_user/dlc_tf1.2

I encounter the following error:
docker: Error response from daemon: Conflict. The container name "/alex_GPU1" is already in use by container "e7f70aa2d12826700481e4dee2de2d57b05d2ebb288d919f3c20e145d52fec8c". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

Is there a work around?

**Comment by AlexEMG** [comment]
that means the container is running. So you can just enter... (perhaps you want do restart it).

**Comment by tfrostig** [comment]
Thanks for the quick reply 

Trying to restart the container lead to the following error: 
Error response from daemon: Cannot restart container alex_GPU1: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=1 --compute --utility --require=cuda>=8.0 --pid=4047 /var/lib/docker/overlay2/893a0c0bfc1f1007287a661b5062393b055196607aa7f4cce1438620c719eda4/merged]\\\\nnvidia-container-cli: device error: unknown device id: 1\\\\n\\\"\"": unknown

And if I just continue according to the instructions I get 

Error response from daemon: Container e499a02fb3ddf3c2dffd10955a07b3f222bcc4cbd1fce60174393affe61f0391 is not running

**Comment by AlexEMG** [comment]
I see - perhaps stop it, then kill it and then create it again.
