### ISSUE TITLE
Problem when running Jupyter notebook from Docker

### ISSUE THREAD

**Issue by emimace** [AlexEMG/Docker4DeepLabCut#5]
Hi,

I installed the Docker4DeepLabCut (following your instructions) on my Linux machine.
It works well, I can connect to Jupyter notebook, but running the code "Docker_TrainNetwork_VideoAnalysis" failed at several instances:
- I had to move the notebook in the folder above /examples otherwise it would not find the module deeplabcut
- then a few more modules were missing in the python of the docker container (ruamel-yaml, opencv, statsmodels). I installed them in the Docker and that fixed the issue.
- now I get an error in the function "deeplabcut.create_training_dataset(path_config_file,Shuffles=[1])" when I try the example config file
the error is : "TypeError: invalid file: PosixPath('/home/emilie/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/config.yaml' "

Can you help me please?
Thanks!

**Comment by MMathisLab** [comment]
this docker works with DLC1 - we recommend using this one, if you are using the pip install package of DLC: https://github.com/MMathisLab/Docker4DeepLabCut2.0
