### ISSUE TITLE
Docker container exits instantly when run

### ISSUE THREAD

**Issue by dehmelt** [AlexEMG/Docker4DeepLabCut#7]
**Error:**
Docker container appears to exit instantly when run. Thus, cannot enter container normally via `GPU=0 bash ./dlc-docker run (...)`.

Issue appears similar to https://github.com/AlexEMG/Docker4DeepLabCut/issues/2, but isn't resolved by adjusting the home directory.

**Server configuration:**
Docker: version 18.09.1, build 4c52b90
GPUs: 2 x NVIDIA GeForce RTX 2080
GPU driver: version 410.79
CUDA: 10.0

**Disclaimer:** :)
I'm fairly new to working with Docker, so I may have made a silly mistake somewhere. Appreciate your help!

**Comments:**
From my superficial attempts at debugging, I initially suspected there may or may not be an issue with the installation of wxPython - but this might simply be a byproduct of my poorly chosen manual entry point. Independently, could the difference in CUDA versions between our server (10.0) and the DLC docker container (8.0) be an issue? _Can I update CUDA and/or the GPU drivers from within the container?_

**Steps to reproduce:**
1. Connected to server, `ssh -X %SERVERNAME`.

2. Created desired home directory, `mkdir $HOME/DeepLabCut`, then `mkdir $HOME/DeepLabCut/DeepHome`.

3. From within $HOME/DeepLabCut, successfully cloned, `git clone https://github.com/MMathisLab/Docker4DeepLabCut2.0`.

4. From within $HOME/DeepLabCut/Docker4DeepLabCut2.0, successfully built image, `docker image build -t $DLCUSER/deepdock .` My chosen $DLCUSER is different from my user name on the network, $NETWORKUSER.

5. Attempted to run container, `GPU=0 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut/DeepHome --name deepdock $DLCUSER/deepdock`. No apparent errors:

```
ret run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut/DeepHome --name deepdock $DLCUSER/deepdock run
1st CMD run

* Setting user name to:             $NETWORKUSER
* Setting user ID to:               5373
* Setting user groups to:           sudo
* Setting password to:              pw
* Setting Notebook port binding to: 2351 (to set manually add -p 2351:8888 as flag)

You can now open the notebook on the host machine by directing your browser to
http://localhost:2351

0 nvidia-docker run -v /home/$NETWORKUSER:/home/$NETWORKUSER -p 52115:22 -p 2351:8888 -e USER_GROUPS=sudo -e USER=$NETWORKUSER -e USER_ID=5373 -e USER_ENCRYPTED_PASSWORD=$PWD -e USER_HOME=/home/$NETWORKUSER -e GPU=0 -e DISPLAY=localhost:10.0 -d -e USER_HOME=$HOME/DeepLabCut/DeepHome --name deepdock $DLCUSER/deepdock
8b522279b5051eaeb9bf3627ca5c6bfbae46a4bcf73b3cfe33c8c2d2f2cafebd
```

6. ...but the container has exited instantly. As in  https://github.com/AlexEMG/Docker4DeepLabCut/issues/2, `docker ps -a` reveals:
```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                     PORTS               NAMES
3666b6cbee76        $DLCUSER/deepdock   "/usr/local/bin/entr…"   3 seconds ago       Exited (1) 2 seconds ago                       deepdock
```

**Comment by dehmelt** [comment]
In an attempt to debug, I **entered the container interactively with a manually set entry point**. Not sure this was helpful, but I'm nonetheless including the output I got, just in case:

7. Suspecting an error upon entry, I decided to run the container interactively while setting a manual entry point: `docker run -it --entrypoint /bin/bash $DLCUSER/deepdock -s`. This worked, insofar as I was now inside the container.

8. Not knowing what exact state the container should be in at this point, I decided to try and run DeepLabCut right away: `ipython`, then `import deeplabcut`. This lead to the following error: 
```
In [1]: import deeplabcut
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-52d2df9c7fa5> in <module>()
----> 1 import deeplabcut

/usr/local/lib/python3.6/dist-packages/deeplabcut/__init__.py in <module>()
     23 else:
     24     mpl.use('TkAgg')
---> 25     from deeplabcut import generate_training_dataset
     26     from deeplabcut import refine_training_dataset
     27

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/__init__.py in <module>()
     13     pass
     14 else:
---> 15     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
     16     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     17     from deeplabcut.generate_training_dataset.frame_extraction_toolbox import *

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py in <module>()
     16
     17 import numpy as np
---> 18 import wx
     19
     20 class DraggablePoint:

ModuleNotFoundError: No module named 'wx'
```

9. Exited iPython. Suspecting that wxPython might not be properly installed at this point, I experimented by trying to mimick the usual order of installation for DeepLabCut. First, `pip install deeplabcut`, which simply informed me that all requirements were already satisfied. Then `pip install wxPython`, which returned the following error:
```
Collecting wxPython
(...)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.6/dist-packages (from wxPython) (1.11.0)
Requirement already satisfied, skipping upgrade: Pillow in /usr/local/lib/python3.6/dist-packages (from wxPython) (5.0.0)
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
(...)
  checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtk+-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gtk+-3.0' found
  Package gthread-2.0 was not found in the pkg-config search path.
(...)
  No package 'gthread-2.0' found
  no
(...)
  The development files for GTK+ were not found.
(...)
  Failed building wheel for wxPython
(...)
```

**Comment by MMathisLab** [comment]
if you are using DLC 2.x., which has wxPython, then you need to use the Docker for DLC2: https://github.com/MMathisLab/Docker4DeepLabCut2.0

**Comment by MMathisLab** [comment]
and, you cannot use the GUIs inside Docker. See the installation guide for the Docker, and please see the user-guide here: https://github.com/MMathisLab/Docker4DeepLabCut2.0#using-the-docker-for-training-and-video-analysis and a video tutorial here: https://www.youtube.com/watch?v=7xwOhUcIGio
