### ISSUE TITLE
docker not running

### ISSUE THREAD

**Issue by xcharxlie** [AlexEMG/Docker4DeepLabCut#8]
I just followed the prompts and instructions to create dockers, when I was trying to enter one of them and execute it, I was told it was not running. No matter how I restarted or reopened it, it kept the same. I am very new to this, thanks for any help in advance.
OS : linux Ubuntu 18.04
CUDA : 10.1
Nvidia Driver:430.26
Docker: the latest edition, forget the exact numbers

Here are the codes and error prompts
(base) david@GireLab4GPU:~/Desktop$ cd Docker4DeepLabCut2.0
(base) david@GireLab4GPU:~/Desktop/Docker4DeepLabCut2.0$  docker start b26014081e28
b26014081e28
(base) david@GireLab4GPU:~/Desktop/Docker4DeepLabCut2.0$ docker exec --user $USER -it charlie  /bin/bash
Error response from daemon: Container b26014081e28f6d0eed6f001c56c9553cb35359f8bf4a4fef90c585130b281e5 is not running
(base) david@GireLab4GPU:~/Desktop/Docker4DeepLabCut2.0$ docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                         PORTS               NAMES
bc7ebee732e9        dlc_username/dlcdocker   "/usr/local/bin/entr…"   20 minutes ago      Exited (1) 19 minutes ago                          dlcc
d198df37b834        debian                   "bash"                   About an hour ago   Up About an hour                                   my_debian
db1f623f2a25        dlc_username/dlcdocker   "/usr/local/bin/entr…"   2 hours ago         Exited (1) About an hour ago                       lab1
b26014081e28        dlc_username/dlcdocker   "/usr/local/bin/entr…"   26 hours ago        Exited (1) 3 minutes ago                           charlie
60b8cc5bed04        hello-world              "/hello"                 26 hours ago        Exited (0) 26 hours ago                            suspicious_merkle
0f8a8027c93f        hello-world              "/hello"                 27 hours ago        Exited (0) 27 hours ago                            awesome_wescoff

**Comment by MMathisLab** [comment]
Can you please post the call you used to build the image then the container? 

Typical error if you are not setting the folder path correctly to $HOME

**Comment by MMathisLab** [comment]
Ps -please tell David hi from Mackenzie ;)

**Comment by xcharxlie** [comment]
Hi, Mackenzie. Sorry that I just left my lab. I would send you the code later tomorrow. 3:0

**Comment by AlexEMG** [comment]
Can you please post this issue in the other container: ( as you are using DLC2.0) https://github.com/AlexEMG/Docker4DeepLabCut2.0
