### ISSUE TITLE
Having trouble with HDF5

### ISSUE THREAD

**Issue by oceansen** [AlexEMG/Docker4DeepLabCut#9]
Hi,

I have been having trouble installing the docker container due to the following error:

docker image build -t dlc_user/dlc_tf1.2 . 
Sending build context to Docker daemon  111.6kB
Step 1/18 : FROM python:3
 ---> 1f88553e8143
Step 2/18 : RUN pip install imageio
 ---> Using cache
 ---> e9cdbef89bf7
Step 3/18 : RUN pip install imageio-ffmpeg #imageio.ffmpeg.download() is deprecated
 ---> Using cache
 ---> 24870b8225a2
Step 4/18 : FROM bethgelab/deeplearning:cuda8.0-cudnn5
 ---> 351b7096caf1
Step 5/18 : RUN apt-get update
 ---> Using cache
 ---> f90b70b88d52
Step 6/18 : RUN apt-get -y install ffmpeg
 ---> Using cache
 ---> 33e4d3825080
Step 7/18 : RUN pip3 install easydict
 ---> Using cache
 ---> 37c707dde349
Step 8/18 : RUN pip install tables #for h5 support
 ---> Running in 5e302ec0ddfb
Collecting tables
  Downloading https://files.pythonhosted.org/packages/2b/32/847ee3f521aae6a0be380d923a736162d698586f444df1ac24b98c65025c/tables-3.6.1.tar.gz (4.6MB)
    Complete output from command python setup.py egg_info:
    /tmp/H5closeyy_rjzhj.c:1:1: warning: return type defaults to 'int' [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    /tmp/H5closeyy_rjzhj.c: In function 'main':
    /tmp/H5closeyy_rjzhj.c:2:5: warning: implicit declaration of function 'H5close' [-Wimplicit-function-declaration]
         H5close();
         ^
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 3.5.2 (default, Nov 17 2016, 17:05:23)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-osglf86i/tables/
You are using pip version 9.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install tables #for h5 support' returned a non-zero code: 1

------
I did install HDF5 on the node.

sagar@g001:~/Docker4DeepLabCut$  ls /usr/lib/x86_64-linux-gnu/ | grep hdf5
hdf5
libhdf5_cpp.a
libhdf5_cpp.so
libhdf5_cpp.so.100
libhdf5_cpp.so.100.0.0
libhdf5_hl_cpp.a
libhdf5_hl_cpp.so
libhdf5_hl_cpp.so.100
libhdf5_hl_cpp.so.100.0.0
libhdf5_openmpi.a
libhdf5_openmpi.settings
libhdf5_openmpi.so
libhdf5_openmpi.so.100
libhdf5_openmpi.so.100.0.1
libhdf5_openmpi_fortran.a
libhdf5_openmpi_fortran.so
libhdf5_openmpi_fortran.so.100
libhdf5_openmpi_fortran.so.100.0.1
libhdf5_openmpi_hl.a
libhdf5_openmpi_hl.so
libhdf5_openmpi_hl.so.100
libhdf5_openmpi_hl.so.100.0.0
libhdf5_openmpihl_fortran.a
libhdf5_openmpihl_fortran.so
libhdf5_openmpihl_fortran.so.100
libhdf5_openmpihl_fortran.so.100.0.0
libhdf5_serial.a
libhdf5_serial.settings
libhdf5_serial.so
libhdf5_serial.so.100
libhdf5_serial.so.100.0.1
libhdf5_serial_fortran.a
libhdf5_serial_fortran.so
libhdf5_serial_fortran.so.100
libhdf5_serial_fortran.so.100.0.1
libhdf5_serial_hl.a
libhdf5_serial_hl.so
libhdf5_serial_hl.so.100
libhdf5_serial_hl.so.100.0.0
libhdf5_serialhl_fortran.a
libhdf5_serialhl_fortran.so
libhdf5_serialhl_fortran.so.100
libhdf5_serialhl_fortran.so.100.0.0

Any help with this would be greatly appreciated.

Regards,

Sagar

**Comment by AlexEMG** [comment]
I think this error is related: https://github.com/DeepLabCut/DeepLabCut/issues/164

Sorry, I'm late -- but we recommend the new docker image now: 
https://github.com/DeepLabCut/DeepLabCut/tree/master/docker
